#define BOX_SPATIAL_DIMENSION 3
#define BOX_PERIODIC 
#define HYDRO_MESHLESS_FINITE_MASS 
#define MAGNETIC 
#define GRAVITY_NOT_PERIODIC 
#define SINGLE_STAR_STARFORGE_DEFAULTS 
#define SINGLE_STAR_STARFORGE_PROTOSTELLAR_EVOLUTION 2
#define SINGLE_STAR_FB_JETS 
#define SINGLE_STAR_FB_WINDS 0
#define SINGLE_STAR_FB_SNE 
#define SINGLE_STAR_FB_RAD 
#define COOLING 
#define COSMIC_RAY_FLUID 
#define INPUT_COSMIC_RAY_ENERGY 
#define CRFLUID_M1 (300000.)
#define CRFLUID_DIFFUSION_MODEL 0
#define RT_SPEEDOFLIGHT_REDUCTION (1.0e-3)
#define CRFLUID_ION_ALFVEN_SPEED 
#define CRFLUID_ALT_RSOL_FORM 
#define OPENMP 2
#define ADAPTIVE_TREEFORCE_UPDATE 0.0625
#define SUBCYCLING_TEST 
